### ISSUE TITLE
Web Configurator for Available API Options

### ISSUE THREAD

**Issue by lewxdev** [kyechan99/capsule-render#19]
It could be nice to create a configurator / utility that generates the render with the respective, available API parameters for easily messing around with the options.
I could see this being a simple, static site deployed to GitHub Pages, and programmatically generating the relevant options from the code via some script and GitHub Actions. Alternatively, the generator can be hosted on Vercel along with the API.

**Comment by kyechan99** [comment]
Are you talking about a generator site where you can easily use the API ?
Like this ? [box-shadow generator](https://cssgenerator.org/box-shadow-css-generator.html)

**Comment by lewxdev** [comment]
@kyechan99 Yep, something similar to that. Any contentions?

**Comment by kyechan99** [comment]
ok. I don't know when it will be, but I'll try.

**Comment by kyechan99** [comment]
It took a really long time. 😭 
Finally, [Generator](https://capsule-render.vercel.app)  was added.
