### ISSUE TITLE
500: INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by yiyungent** [kyechan99/capsule-render#22]
https://capsule-render.vercel.app/api?type=waving&color=timeGradient&height=200&section=header&reversal=true&animation=twinkling&fontSize=70&fontAlignY=30&descAlignY=50&text=KnifeHub&desc=%F0%9F%A7%B0%20%E7%AE%80%E5%8D%95%E6%98%93%E7%94%A8%E7%9A%84%E6%95%88%E7%8E%87%E5%B7%A5%E5%85%B7%E5%B9%B3%E5%8F%B0

```url
https://capsule-render.vercel.app/api?type=waving&color=timeGradient&height=200&section=header&reversal=true&animation=twinkling&fontSize=70&fontAlignY=30&descAlignY=50&text=KnifeHub&desc=🧰%20简单易用的效率工具平台
```

I don't know why this URL was working fine before, but recently it returns a `500` error. Can you help me resolve this? 
Thank you.

![image](https://github.com/kyechan99/capsule-render/assets/16939388/0ede861a-dedc-4556-bb0a-61427abf8d3c)

**Comment by kyechan99** [comment]
![ㅁ](https://capsule-render.vercel.app/api?type=waving&color=timeGradient&height=200&section=header&reversal=true&animation=twinkling&fontSize=70&fontAlignY=30&descAlignY=50&text=KnifeHub&desc=%F0%9F%A7%B0%20%E7%AE%80%E5%8D%95%E6%98%93%E7%94%A8%E7%9A%84%E6%95%88%E7%8E%87%E5%B7%A5%E5%85%B7%E5%B9%B3%E5%8F%B0)

OMG! 
I just urgently fixed a bug.
It should work fine for now.

**Comment by yiyungent** [comment]
Thank you very much, everything is normal now !
