### ISSUE TITLE
Custom list of random colors

### ISSUE THREAD

**Issue by kauer3** [kyechan99/capsule-render#4]
Is there a way of editing the list of random colors? Actually, in my case I am more interested in editing the list of random gradients. Alternatively, setting a fixed gradient would also be nice.

**Comment by kyechan99** [comment]
Thank you for your interest. 😄

As you said, it would be nice to have a function to set a fixed gradient. 
I will add it soon.
If there is a query or method you want, please recommend it.

On the other hand, 
> "Is there a way of editing the list of random colors?"

Is it mean customization random list like [your commit](https://github.com/kauer3/capsule-render/commit/98b6cf4e35fb337c44a657fac707424ab395d2d3) ?

If that's the case, full customization seems a bit difficult. But how about this way?

```json
// gradient.json file
[
    {
        "number": 0,     // add unique number
        "color": {  },
        "text": "...",
        "textBg": " ..."
    },
    {
        "number": 1,
        "color": {  },
        "text": "...",
        "textBg": "..."
    },
    ...
]
```

And use like this.
```
https://.../api?color=gradient&colorList=0,1
```
Setting list of random colors **to add unique numbers of the desired color scheme in the query**.

**Comment by kauer3** [comment]
Hey, thanks for your response!

> But how about this way?

This is actually even better, because you could select the colors that fit each element. It would be perfect in my case, as I'm trying to use it to create some drawings.

Looking forward to the update. Keep up the great work! 😄
